#ifndef SCOPIC_FLOW_SCOPICFLOWGLOBAL_H
#define SCOPIC_FLOW_SCOPICFLOWGLOBAL_H

#ifndef SCOPIC_FLOW_EXPORT
#  ifdef SCOPIC_FLOW_STATIC
#    define SCOPIC_FLOW_EXPORT
#  else
#    ifdef SCOPICFLOW_LIBRARY
#      define SCOPIC_FLOW_EXPORT Q_DECL_EXPORT
#    else
#      define SCOPIC_FLOW_EXPORT Q_DECL_IMPORT
#    endif
#  endif
#endif

#endif //SCOPIC_FLOW_SCOPICFLOWGLOBAL_H
